# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: We set up the website
email: andrew.alcaraz.851@my.csun.edu
description: > # this means to ignore newlines until "baseurl:"
 Im just a new user looking to get a job in IT database administrators.
testing this line for darwin project

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://andrewalcaraz.com" # the base hostname & protocol for your site
twitter_username: superrandom421
github_username:  aalcaraz

# Build settings
markdown: kramdown
