# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Welcome To My CIT480 Senior Design Class Blog
email: andrew.alcaraz.851@my.csun.edu
description: > # this means to ignore newlines until "baseurl:"
  Hello and welcome to my blog for cit480 this semester, Evrey few weeks I 
  will be posting documention on new technology I've learned here at Cal State
  Northridge or at my job. Thank you for coming to visit my site and have bless day.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: SuperRandom
github_username:  aalcaraz851

# Build settings
markdown: kramdown
