# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"

 Hello im andrew alcaraz the maker of the site. this is lab1 part B.

 You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/descript" # the subpath of your site, e.g. /blog
url: "404.html" # the base hostname & protocol for your site
twitter_username: superradom420
github_username:  aalcaarz.851

# Build settings
markdown: kramdown
